repos:
- repo: meta
  hooks:
    - id: check-hooks-apply
    - id: check-useless-excludes
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.0.1
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.7.1
  hooks:
    - id: check-github-workflows
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      additional_dependencies: ['flake8-bugbear==21.4.3']
- repo: https://github.com/python/black
  rev: 21.11b1
  hooks:
    - id: black
- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
    - id: isort
- repo: https://github.com/asottile/pyupgrade
  rev: v2.29.1
  hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
